name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    environment: snowfall workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI (API Token)
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        #env:
        #  TWINE_USERNAME: ${{ github.actor }}
        #  TWINE_PASSWORD: ${{ secrets.GH_PAT }}
